apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
# resources:
# - ../../base
helmCharts:
- name: sealed-secrets
  releaseName: sealed-secrets
  repo: https://bitnami-labs.github.io/sealed-secrets
  version: 2.16.2