apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane
# resources:
# - ../../base
helmCharts:
- name: crossplane
  releaseName: crossplane
  repo: https://charts.crossplane.io/stable
  version: 1.19.0-rc.0.77.g184951c4b
  valuesInline:
      provider:
        packages:
          - xpkg.upbound.io/crossplane-contrib/provider-aws:v0.39.0
